# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1061)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imgDirRoot_label = QtWidgets.QLabel(self.centralwidget)
        self.imgDirRoot_label.setGeometry(QtCore.QRect(20, 40, 150, 22))
        self.imgDirRoot_label.setTextFormat(QtCore.Qt.RichText)
        self.imgDirRoot_label.setAlignment(QtCore.Qt.AlignCenter)
        self.imgDirRoot_label.setIndent(0)
        self.imgDirRoot_label.setObjectName("imgDirRoot_label")
        self.sub_dir_label = QtWidgets.QLabel(self.centralwidget)
        self.sub_dir_label.setGeometry(QtCore.QRect(79, 80, 91, 22))
        self.sub_dir_label.setTextFormat(QtCore.Qt.RichText)
        self.sub_dir_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sub_dir_label.setIndent(0)
        self.sub_dir_label.setObjectName("sub_dir_label")
        self.set_root = QtWidgets.QPushButton(self.centralwidget)
        self.set_root.setGeometry(QtCore.QRect(760, 40, 75, 23))
        self.set_root.setObjectName("set_root")
        self.imgDirRoot = QtWidgets.QComboBox(self.centralwidget)
        self.imgDirRoot.setGeometry(QtCore.QRect(180, 40, 571, 22))
        self.imgDirRoot.setObjectName("imgDirRoot")
        self.Image_name = QtWidgets.QLabel(self.centralwidget)
        self.Image_name.setGeometry(QtCore.QRect(60, 120, 111, 22))
        self.Image_name.setTextFormat(QtCore.Qt.RichText)
        self.Image_name.setAlignment(QtCore.Qt.AlignCenter)
        self.Image_name.setIndent(0)
        self.Image_name.setObjectName("Image_name")
        self.img_list = QtWidgets.QComboBox(self.centralwidget)
        self.img_list.setGeometry(QtCore.QRect(180, 120, 571, 21))
        self.img_list.setIconSize(QtCore.QSize(20, 20))
        self.img_list.setObjectName("img_list")
        self.show_Fullimg = QtWidgets.QPushButton(self.centralwidget)
        self.show_Fullimg.setGeometry(QtCore.QRect(760, 120, 75, 23))
        self.show_Fullimg.setObjectName("show_Fullimg")
        self.fullimg_window = QtWidgets.QScrollArea(self.centralwidget)
        self.fullimg_window.setGeometry(QtCore.QRect(60, 190, 771, 801))
        self.fullimg_window.setMouseTracking(True)
        self.fullimg_window.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.fullimg_window.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.fullimg_window.setWidgetResizable(True)
        self.fullimg_window.setObjectName("fullimg_window")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 769, 799))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.fullimg_window.setWidget(self.scrollAreaWidgetContents)
        self.fullimg = QtWidgets.QLabel(self.centralwidget)
        self.fullimg.setGeometry(QtCore.QRect(60, 163, 281, 20))
        self.fullimg.setTextFormat(QtCore.Qt.RichText)
        self.fullimg.setObjectName("fullimg")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(60, 150, 771, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.sub_dir_list = QtWidgets.QComboBox(self.centralwidget)
        self.sub_dir_list.setGeometry(QtCore.QRect(180, 80, 571, 21))
        self.sub_dir_list.setIconSize(QtCore.QSize(20, 20))
        self.sub_dir_list.setObjectName("sub_dir_list")
        self.saveDirRoot = QtWidgets.QComboBox(self.centralwidget)
        self.saveDirRoot.setGeometry(QtCore.QRect(1200, 120, 491, 22))
        self.saveDirRoot.setObjectName("saveDirRoot")
        self.saveDirRoot_label = QtWidgets.QLabel(self.centralwidget)
        self.saveDirRoot_label.setGeometry(QtCore.QRect(1070, 120, 111, 22))
        self.saveDirRoot_label.setTextFormat(QtCore.Qt.RichText)
        self.saveDirRoot_label.setAlignment(QtCore.Qt.AlignCenter)
        self.saveDirRoot_label.setIndent(0)
        self.saveDirRoot_label.setObjectName("saveDirRoot_label")
        self.edgecolor_label = QtWidgets.QLabel(self.centralwidget)
        self.edgecolor_label.setGeometry(QtCore.QRect(1330, 80, 110, 22))
        self.edgecolor_label.setTextFormat(QtCore.Qt.RichText)
        self.edgecolor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.edgecolor_label.setIndent(0)
        self.edgecolor_label.setObjectName("edgecolor_label")
        self.edgeWidthLine = QtWidgets.QLineEdit(self.centralwidget)
        self.edgeWidthLine.setGeometry(QtCore.QRect(1200, 80, 91, 20))
        self.edgeWidthLine.setObjectName("edgeWidthLine")
        self.edge_colorcbox = QtWidgets.QComboBox(self.centralwidget)
        self.edge_colorcbox.setGeometry(QtCore.QRect(1450, 80, 91, 20))
        self.edge_colorcbox.setStyleSheet("")
        self.edge_colorcbox.setObjectName("edge_colorcbox")
        self.edge_colorcbox.addItem("")
        self.edge_colorcbox.addItem("")
        self.edge_colorcbox.addItem("")
        self.edgeWidth_label = QtWidgets.QLabel(self.centralwidget)
        self.edgeWidth_label.setGeometry(QtCore.QRect(1080, 80, 110, 22))
        self.edgeWidth_label.setTextFormat(QtCore.Qt.RichText)
        self.edgeWidth_label.setAlignment(QtCore.Qt.AlignCenter)
        self.edgeWidth_label.setIndent(0)
        self.edgeWidth_label.setObjectName("edgeWidth_label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(1080, 150, 791, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.crop_viewbt = QtWidgets.QPushButton(self.centralwidget)
        self.crop_viewbt.setGeometry(QtCore.QRect(870, 410, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(14)
        self.crop_viewbt.setFont(font)
        self.crop_viewbt.setObjectName("crop_viewbt")
        self.save_finalbt = QtWidgets.QPushButton(self.centralwidget)
        self.save_finalbt.setGeometry(QtCore.QRect(1780, 79, 81, 61))
        self.save_finalbt.setStyleSheet("font: 57 14pt \"Ubuntu Light\";")
        self.save_finalbt.setObjectName("save_finalbt")
        self.set_Saveroot_bt = QtWidgets.QPushButton(self.centralwidget)
        self.set_Saveroot_bt.setGeometry(QtCore.QRect(1700, 120, 71, 23))
        self.set_Saveroot_bt.setObjectName("set_Saveroot_bt")
        self.resize_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.resize_combobox.setGeometry(QtCore.QRect(1650, 80, 121, 20))
        self.resize_combobox.setStyleSheet("")
        self.resize_combobox.setObjectName("resize_combobox")
        self.resize_combobox.addItem("")
        self.resize_combobox.addItem("")
        self.resize_combobox.addItem("")
        self.resizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.resizeLabel.setGeometry(QtCore.QRect(1560, 80, 91, 22))
        self.resizeLabel.setTextFormat(QtCore.Qt.RichText)
        self.resizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resizeLabel.setIndent(0)
        self.resizeLabel.setObjectName("resizeLabel")
        self.patchTab = QtWidgets.QTabWidget(self.centralwidget)
        self.patchTab.setGeometry(QtCore.QRect(1090, 170, 781, 821))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.patchTab.setFont(font)
        self.patchTab.setObjectName("patchTab")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.patchTab.setCurrentIndex(-1)
        self.set_root.clicked.connect(self.set_root.showMenu)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.imgDirRoot_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Image Dir Root:</span></p></body></html>"))
        self.sub_dir_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt;\">Sub Dirs:</span></p></body></html>"))
        self.set_root.setText(_translate("MainWindow", "Browser"))
        self.Image_name.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt;\">Image Name:</span></p></body></html>"))
        self.show_Fullimg.setText(_translate("MainWindow", "Preview"))
        self.fullimg.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">HR image will be shown here.</span></p></body></html>"))
        self.saveDirRoot_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Save Dir:</span></p></body></html>"))
        self.edgecolor_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Edge Color:</span></p></body></html>"))
        self.edgeWidthLine.setText(_translate("MainWindow", "15"))
        self.edge_colorcbox.setItemText(0, _translate("MainWindow", "Blue"))
        self.edge_colorcbox.setItemText(1, _translate("MainWindow", "Red"))
        self.edge_colorcbox.setItemText(2, _translate("MainWindow", "Orange"))
        self.edgeWidth_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Edge Width:</span></p></body></html>"))
        self.crop_viewbt.setText(_translate("MainWindow", "Crop View >>"))
        self.save_finalbt.setText(_translate("MainWindow", "Save"))
        self.set_Saveroot_bt.setText(_translate("MainWindow", "Browser"))
        self.resize_combobox.setItemText(0, _translate("MainWindow", "Crop square area"))
        self.resize_combobox.setItemText(1, _translate("MainWindow", "Keep dimension"))
        self.resize_combobox.setItemText(2, _translate("MainWindow", "Resize to square"))
        self.resizeLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Resize:</span></p></body></html>"))
